stages:
    - build
    - test
    - docker_build

build:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    stage: build
    script:
        - "dotnet build ./src"
    artifacts:
      paths:
        - bin/

test:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    stage: test
    script: 
        - "dotnet test ./src"